// Imported via the `@videos/*` tsconfig alias (→ ./videos/*) because Turbopack —
// Next 16's default bundler — doesn't resolve bare `/videos/*` specifiers. The
// `withNextVideo` turbopack rule then rewrites each `.mp4` into a Mux-backed asset.
import typeSans from "@videos/type-sans.mp4";
import colorsReel from "@videos/colors-reel.mp4";
import docsFocus from "@videos/docs-focus.mp4";
import docsScroll from "@videos/docs-scroll.mp4";
import docsBrowse from "@videos/docs-browse.mp4";
import docsSearch from "@videos/docs-search.mp4";
import docsLoop from "@videos/docs-loop.mp4";
import docsTypeDemo from "@videos/docs-type-demo.mp4";
import docsSpecPortrait from "@videos/docs-spec-portrait.mp4";
import docsSpecBanner from "@videos/docs-spec-banner.mp4";
import docsSpecHairline from "@videos/docs-spec-hairline.mp4";
import docsSpecHeavy from "@videos/docs-spec-heavy.mp4";
import docsSpecNeon from "@videos/docs-spec-neon.mp4";
import docsSpecMono from "@videos/docs-spec-mono.mp4";
import docsSpecLowercase from "@videos/docs-spec-lowercase.mp4";
import docsSpecSymbols from "@videos/docs-spec-symbols.mp4";
import docsSpecOneshot from "@videos/docs-spec-oneshot.mp4";
import docsIconsShowcase from "@videos/docs-icons-showcase.mp4";
import docsIconsOneatatime from "@videos/docs-icons-oneatatime.mp4";
import docsIconsPattern from "@videos/docs-icons-pattern.mp4";
import docsIconsLayered from "@videos/docs-icons-layered.mp4";
import docsWall from "@videos/docs-wall.mp4";
import docsWallTest from "@videos/docs-wall-test.mp4";
import docsHome from "@videos/docs-home.mp4";
import docsVertical from "@videos/docs-vertical.mp4";
import docsStraight from "@videos/docs-straight.mp4";
import lookbookWall from "@videos/lookbook-wall.mp4";

/**
 * The example clips shown in the docs, keyed by a stable slug. Every clip is
 * generated by pro-visu from the FASHION storefront in `apps/testing` — see
 * `apps/docs/videos.md` for the regenerate workflow. Imports live in this
 * plain module (not in MDX) so next-video's loader reliably rewrites the `.mp4`
 * imports into Mux-backed assets and MDX pages stay import-free.
 */
export const clips = {
  "type-sans": typeSans,
  "docs-wall": docsWall,
  "docs-home": docsHome,
  "docs-focus": docsFocus,
  "colors-reel": colorsReel,
  "docs-scroll": docsScroll,
  "docs-browse": docsBrowse,
  "docs-search": docsSearch,
  "docs-loop": docsLoop,
  "lookbook-wall": lookbookWall,
  "docs-straight": docsStraight,
  "docs-vertical": docsVertical,
  "docs-wall-test": docsWallTest,
  "docs-type-demo": docsTypeDemo,
  "docs-spec-portrait": docsSpecPortrait,
  "docs-spec-banner": docsSpecBanner,
  "docs-spec-hairline": docsSpecHairline,
  "docs-spec-heavy": docsSpecHeavy,
  "docs-spec-neon": docsSpecNeon,
  "docs-spec-mono": docsSpecMono,
  "docs-spec-lowercase": docsSpecLowercase,
  "docs-spec-symbols": docsSpecSymbols,
  "docs-spec-oneshot": docsSpecOneshot,
  "docs-icons-showcase": docsIconsShowcase,
  "docs-icons-oneatatime": docsIconsOneatatime,
  "docs-icons-pattern": docsIconsPattern,
  "docs-icons-layered": docsIconsLayered,
} as const;

export type ClipName = keyof typeof clips;
