import Image from "next/image";
import Video from "next-video";
import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock";
import { clips, type ClipName } from "@/components/clips";

export interface ExampleProps {
  /** The pro-visu config snippet shown next to the output. */
  code: string;
  /** Language for syntax highlighting. Defaults to `ts`. */
  lang?: string;
  /** Which generated clip to show (a key from `components/clips.ts`). */
  clip: ClipName;
  /** Optional one-line caption under the example. */
  caption?: string;
  /** For tall (e.g. 9:16) clips: cap the height and centre it instead of filling the width. */
  portrait?: boolean;
}

/**
 * Pairs a pro-visu config snippet with the asset it produces — the docs' way of
 * showing "this config → this output". Every clip is generated by pro-visu itself
 * (dogfooding the VESPER storefront in `apps/testing`) and served through
 * next-video / Mux. Authored in MDX with no imports:
 *
 * ```mdx
 * <Example
 *   clip="hero-loop"
 *   caption="A seamless boomerang hero loop."
 *   code={`{ name: "hero", url: "https://your-site.com", generator: "scroll-reel" }`}
 * />
 * ```
 */
export function Example({ code, lang = "ts", clip, caption, portrait }: ExampleProps) {
  const video = clips[clip];
  return (
    <figure className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-fd-card">
      <div className="grid gap-px bg-fd-border md:grid-cols-2">
        <div className="min-w-0 bg-fd-card [&_figure]:m-0 [&_pre]:max-h-[26rem] [&_pre]:rounded-none">
          <DynamicCodeBlock lang={lang} code={code} />
        </div>
        <div className="flex items-center justify-center bg-black">
          <Video
            src={video}
            autoPlay
            loop
            muted
            playsInline
            className={portrait ? "mx-auto h-auto max-h-[30rem] w-auto" : "h-auto w-full"}
          />
        </div>
      </div>
      {caption ? (
        <figcaption className="border-t border-fd-border px-4 py-2 text-sm text-fd-muted-foreground">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  );
}

export interface ImageExampleProps {
  /** The pro-visu config snippet shown next to the output. */
  code: string;
  /** Language for syntax highlighting. Defaults to `ts`. */
  lang?: string;
  /** Public path to the still, e.g. `/examples/docs-palette.png`. */
  src: string;
  /** Intrinsic pixel dimensions of the image (next/image needs them for the ratio). */
  width: number;
  height: number;
  /** Alt text. */
  alt: string;
  /** Optional one-line caption under the example. */
  caption?: string;
  /**
   * For very tall stills (e.g. a full-page screenshot): cap the output panel height and let it
   * scroll, so the example shows the whole page is captured without dominating the article.
   */
  tall?: boolean;
}

/**
 * The still-image sibling of {@link Example} — config snippet next to a `next/image` of the asset
 * it produces (palette grids, screenshots). Stills live in `public/examples/`; see
 * `apps/docs/videos.md`.
 */
export function ImageExample({ code, lang = "ts", src, width, height, alt, caption, tall }: ImageExampleProps) {
  return (
    <figure className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-fd-card">
      <div className="grid gap-px bg-fd-border md:grid-cols-2">
        <div className="min-w-0 bg-fd-card [&_figure]:m-0 [&_pre]:max-h-[26rem] [&_pre]:rounded-none">
          <DynamicCodeBlock lang={lang} code={code} />
        </div>
        <div
          className={`flex justify-center bg-black ${
            tall ? "max-h-[26rem] items-start overflow-y-auto" : "items-center"
          }`}
        >
          <Image
            src={src}
            width={width}
            height={height}
            alt={alt}
            sizes="(min-width: 768px) 50vw, 100vw"
            className="h-auto w-full"
          />
        </div>
      </div>
      {caption ? (
        <figcaption className="border-t border-fd-border px-4 py-2 text-sm text-fd-muted-foreground">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  );
}

export interface ShowcaseProps {
  /** Which clip to show (a key from `components/clips.ts`). */
  clip: ClipName;
  /** Optional caption under the clip. */
  caption?: string;
}

/**
 * A full-width hero clip with no code panel — for the landing page, where the point is to *show*
 * what pro-visu produces, not how it's configured.
 */
export function Showcase({ clip, caption }: ShowcaseProps) {
  return (
    <figure className="not-prose my-6 overflow-hidden rounded-xl border border-fd-border bg-black">
      <Video src={clips[clip]} autoPlay loop muted playsInline className="h-auto w-full" />
      {caption ? (
        <figcaption className="border-t border-fd-border bg-fd-card px-4 py-2 text-sm text-fd-muted-foreground">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  );
}
