import type { ZodTypeAny } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

import { TOOL_VERSION } from "@/version";
import { listGenerators } from "@/generators/registry";
import { settingsSchema, captureOverrideSchema } from "@/config/schema";

type JsonObject = Record<string, unknown>;

/** Convert a zod schema to an inlined (no $ref) JSON Schema fragment, without its own $schema tag. */
function toJson(schema: ZodTypeAny): JsonObject {
  const out = zodToJsonSchema(schema, { $refStrategy: "none" }) as JsonObject; //EXCUSE: narrowing the library's broad return type to a plain object
  delete out.$schema;
  return out;
}

/**
 * Build a draft-07 JSON Schema for a `pro-visu.config.json`, assembled from the live, registered
 * schemas. A JSON config that references it via `$schema` then gets the same editor autocomplete +
 * validation as the typed `defineConfig` path — with no project dependency on this package.
 *
 * Per-generator `options` autocomplete comes from a discriminated union: once `generator` is set,
 * the matching `allOf` branch refines `options` to that generator's own schema. Because it's built
 * from the registry at runtime, `pro-visu init --json` / `pro-visu schema` materialize a schema that
 * always matches the installed tool version (works offline and in any install mode).
 */
export function generateConfigJsonSchema(): JsonObject {
  const generators = listGenerators();

  const optionBranches = generators.map((gen) => ({
    if: { properties: { generator: { const: gen.id } } },
    then: { properties: { options: toJson(gen.optionsSchema) } },
  }));

  const assetItem: JsonObject = {
    type: "object",
    required: ["name", "generator"],
    additionalProperties: false,
    properties: {
      name: { type: "string", minLength: 1, description: "Unique id — also the output filename and manifest key." },
      enabled: {
        type: ["boolean", "string"],
        default: true,
        description:
          'Run this asset? true (default), false to skip it, or a group string (e.g. "quick-test") selected via settings.enabled.',
      },
      url: {
        type: "string",
        description:
          "Absolute http(s) URL, or a /path resolved against the managed server. Omit for local generators (wall, specimen, palette).",
      },
      generator: { description: "Which generator produces this asset.", enum: generators.map((g) => g.id) },
      options: { type: "object", description: "Generator-specific options — autocompletes once `generator` is set." },
      capture: {
        ...toJson(captureOverrideSchema),
        description:
          "Per-asset overrides of settings.capture, merged over it for this asset only (cleanup arrays are additive; showSelectors/unblockHosts subtract).",
      },
    },
    allOf: optionBranches,
  };

  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "pro-visu config",
    description: "Configuration for the pro-visu CLI (pro-visu.config.json).",
    "x-tool-version": TOOL_VERSION,
    type: "object",
    required: ["assets"],
    additionalProperties: false,
    properties: {
      $schema: { type: "string" },
      settings: toJson(settingsSchema),
      assets: { type: "array", minItems: 1, description: "What to generate (at least one).", items: assetItem },
    },
  };
}

/** Serialize the JSON Schema document for writing to disk. */
export function serializeConfigJsonSchema(): string {
  return `${JSON.stringify(generateConfigJsonSchema(), null, 2)}\n`;
}

/** The scaffolded schema filename (`pro-visu init --json` writes it next to the JSON config). */
export const DEFAULT_SCHEMA_FILE = "pro-visu.schema.json";

/**
 * Keep a scaffolded `pro-visu.schema.json` current: if one exists in `dir` and was generated by a
 * different tool version, rewrite it. Runs on every `generate`/`doctor`, so editor autocomplete
 * for JSON configs always matches the installed version with no manual refresh step. Best-effort —
 * a failure never breaks the command.
 */
export async function refreshSchemaFile(dir: string, log?: { info(msg: string): void }): Promise<void> {
  const { readFile, writeFile } = await import("node:fs/promises");
  const path = await import("node:path");
  const file = path.join(dir, DEFAULT_SCHEMA_FILE);
  let existing: string;
  try {
    existing = await readFile(file, "utf8");
  } catch {
    return;
  }
  try {
    const version = (JSON.parse(existing) as Record<string, unknown>)["x-tool-version"]; //EXCUSE: JSON.parse returns `any`; a bad file falls through to the catch
    if (version === TOOL_VERSION) return;
    await writeFile(file, serializeConfigJsonSchema(), "utf8");
    log?.info(`refreshed ${DEFAULT_SCHEMA_FILE} for pro-visu ${TOOL_VERSION}`);
  } catch {}
}
